### ISSUE TITLE
Why does the logger override the global logger?

### ISSUE THREAD

**Issue by Gregliest** [JuliaGPU/GPUCompiler.jl#271] opened 2021-12-16 19:23 UTC
[Here](https://github.com/JuliaGPU/GPUCompiler.jl/blob/master/src/utils.jl#L39-L44) this library overrides the global logger to print to the console. This bypasses all other checks and mechanisms (such as from a custom logger), which means that the user of this library does not have control over these logging statements, except via the `min_level` setting. Thus, if I want to debug my code, with debug level set to DEBUG, my console will be interspersed with the debug statements from this library. 

Is there a way to turn these statements off without changing the logging level? Also, why does this library override the global logger in the first place? It seems like it should just feed into the existing logging hierarchy instead.

**Comment by maleadt** [comment] 2021-12-16 21:13
Those print macros are only used in the implementation of the compiler, where task switches are disallowed. That means any regular I/O doesn't work, including any user logger that would support filtering.



> Thus, if I want to debug my code, with debug level set to DEBUG, my console will be interspersed with the debug statements from this library.

Then set the debug level only for your package? e.g. `JULIA_DEBUG=CUDA` instead of `JULIA_DEBUG=all`.

**Comment by Gregliest** [comment] 2021-12-17 01:25
Thanks for the quick reply! I'm just getting  spun up on how the Julia logger works, and I think I'm misunderstanding something here. 

>  Then set the debug level only for your package? e.g. JULIA_DEBUG=CUDA instead of JULIA_DEBUG=all.

I'm working from the REPL and setting `ENV["JULIA_DEBUG"]=Main` doesn't seem to help. Is there something else I should be setting this env variable to? 

> Those print macros are only used in the implementation of the compiler, where task switches are disallowed. That means any regular I/O doesn't work, including any user logger that would support filtering.

What are the cases where regular I/O doesn't work? I built a custom logger, and I expected to be able to filter all logging messages in `Logger.shouldlog`. Is that not how that function is supposed to be used though? 

Thanks for your help!

**Comment by maleadt** [comment] 2021-12-17 16:41
> I'm working from the REPL and setting `ENV["JULIA_DEBUG"]=Main` doesn't seem to help. Is there something else I should be setting this env variable to?

Ah I'm not sure how to correctly set it up for Main from the REPL; you'll probably need to have a look at the Logging code.

> What are the cases where regular I/O doesn't work?

In the compiler, where task switches are disallowed. You shouldn't have to think about this, but GPUCompiler.jl does.

**Comment by Gregliest** [comment] 2021-12-17 17:07
Hmm, ok, so I shouldn't be seeing these debug statements then. I'm only seeing these debug statements when I run my code line by line in Vscode. When I run it as a block, or the whole file as a script, I don't see them. I guess something about compiling the line individually is calling the pathway for this macro?

**Comment by maleadt** [comment] 2021-12-20 06:49
> Hmm, ok, so I shouldn't be seeing these debug statements then.

No, you will see them when you set `JULIA_DEBUG=all`. I don't see what's wrong with GPUCompiler printing log messages when you request it to, and the fact that we use a custom logger has a good reason (see above), so I think I'll close this bug report.

> I guess something about compiling the line individually is calling the pathway for this macro?

VScode probably handles log output differently?

**Closed by maleadt** 2021-12-20 06:49 UTC

**Comment by Gregliest** [comment] 2021-12-20 17:11
Ok, I think it's against the design intentions of the logging system. However, as you say, there's a good reason, and the case is pretty limited, so closing seems reasonable to me. Thanks for your help!

**Comment by maleadt** [comment] 2021-12-20 17:12
The only alternative I see is not using the logging system at all, which seems even worse :slightly_smiling_face: But happy to consider any alternatives.

**Comment by Gregliest** [comment] 2021-12-20 18:05
Yeah I don't have any better suggestions of the top of my head. But do you have a test case that shows the use case for this code? If I have time I might be able to play around with it.

**Comment by maleadt** [comment] 2021-12-21 08:14
The issue is essentially https://github.com/JuliaLang/julia/issues/18568. I can't reproduce easily right now on 1.7, presumably because there's some lock elision going on, but the issue still occurs with more complicated compiler functionality (not only generated functions, but also inference callbacks, etc).

**Comment by ericphanson** [comment] 2021-12-28 17:39
I wonder if a try-finally block should be used in https://github.com/JuliaGPU/GPUCompiler.jl/blob/4f51c3d542761fe964f4a6cbb031cd025025ea59/src/utils.jl#L39-L44 to ensure the global logger is reset even if the code errors?

**Comment by maleadt** [comment] 2021-12-29 08:56
Errors should be handled by the log macros themselves:

```
julia> function foo()
       @info error()
       42
       end

julia> foo()
┌ Error: Exception while generating log record in module Main at REPL[3]:2
...
└ @ Main REPL[3]:2
42
```
